import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Generals/Navbar";
import Footer from "@/Components/Generals/Footer";
import { Suspense } from "react";
import Loading from "./loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative overflow-x-clip antialiased min-h-screen flex flex-col text-sm md:text-base`}
      >
        <Navbar />
        <main className="flex-grow min-h-screen">
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
        </main>
        <footer className="bg-transparent pt-6">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
