
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Generals/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid-rows-[auto, 1fr, auto]`}
      >
        <header className="px-4 sm:px-8 md:px-16 lg:px-32 overflow-x-hidden  xl:px-64 max-w-7xl w-full mx-auto min-h-screen">
          <Navbar />
        </header>
<main className="px-4 sm:px-8 md:px-16 lg:px-32 overflow-x-hidden  xl:px-64 max-w-7xl w-full mx-auto min-h-screen">
{children}
</main>
<footer className=" bg-gray-700 px-4 sm:px-8 md:px-16 lg:px-32 overflow-x-hidden  xl:px-64 max-w-7xl w-full mx-auto min-h-screen">
footer
</footer>
      </body>
    </html>
  );
}
